// For the zkvm target: types and function declarations from zkvm_accelerators.h,
// generated by bindgen in the zkvm-interface crate. This ensures they always
// exactly match the C standard header: if ziskos exports a function with an
// incompatible signature, this causes a compile-time type error at the call sites.
pub use zisk_zkvm_interface::*;

#[cfg(all(not(all(target_os = "zkvm", target_vendor = "zisk")), zisk_hints))]
extern "C" {
    pub fn pause_hints() -> bool;

    pub fn resume_hints();
}
